import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "./Users.module.css";

// CSR Example
export default function Users() {
  const [users, setUsers] = useState([]);
  useEffect(() => {
    axios.get("/api/users").then((resp) => setUsers(resp.data));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Users Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        {users.map((user, i) => (
          <ul key={i}>
            <li>
              <b> name: </b> {user.name}
            </li>
            <li>
              <b> gender: </b> {user.gender}
            </li>
            <li>
              <b> posts: </b> {JSON.stringify(user["posts"])}
            </li>
          </ul>
        ))}
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
