import Head from "next/head";
import styles from "./Users.module.css";
import { getUsers } from "/pages/api/users";

// SSR Example
export const getServerSideProps = async () => {
  const users = await getUsers();
  return {
    props: {
      users,
    },
  };
};

// Users React Component
export default function Users({ users }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Users Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        {users.map((user, i) => (
          <ul key={i}>
            <li>
              <b> name: </b> {user.name}
            </li>
            <li>
              <b> gender: </b> {user.gender}
            </li>
            <li>
              <b> posts: </b> {JSON.stringify(user["posts"])}
            </li>
          </ul>
        ))}
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
